### ISSUE TITLE
Conflicts with Mur'Neth NPC mod?

### ISSUE THREAD

**Issue by willardthor** [AstroBryGuy/NeeraBanters#1]
I just got an error when trying to install this mod on a "fresh" installation of BG1:EE. (fresh, as in I just installed the game, and applied a few other mods to it).

It seems to have something to do with the Mur'Neth NPC mod I installed.

[What else could cause this error?](http://gibberlings3.net/forums/index.php?showtopic=27741&p=247719)

[SETUP-NEERABANTERS.DEBUG.txt](https://github.com/AstroBryGuy/NeeraBanters/files/532212/SETUP-NEERABANTERS.DEBUG.txt)

**Comment by willardthor** [comment]
I tried again with a different set of mods, and got a different error.

[SETUP-NEERABANTERS.DEBUG.txt](https://github.com/AstroBryGuy/NeeraBanters/files/537278/SETUP-NEERABANTERS.DEBUG.txt)

**Comment by AstroBryGuy** [comment]
You're trying to install the "in development" files rather than the latest release. There are syntax errors in the "in development" files.

Use the latest release - https://github.com/AstroBryGuy/NeeraBanters/releases
